### DISCUSSION TITLE
Alerts works only manualy

### DISCUSSION THREAD

**Discussion by NoFWayMan** [metalmatze/alertmanager-bot#143] [Help/Support]
Hi! I used a docker container with bolt storage, and when i start alertmanager-bot container - it sends me alerts, that allready in "firing" status at prometheus "Alerts" page.
But after that bot stops sending me alerts automaticly, only if i type /alerts in Telegram chat.
What can be the problem?

**Comment by metalmatze** [comment]
How often is Prometheus /  Alertmanager configured to send alerts?

**Comment by NoFWayMan** [comment]
30 seconds for "resolve_timeout" in alertmanager.conf

```
global:
  resolve_timeout: 30s
route:
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'alertmananger-bot'
receivers:
- name: 'alertmananger-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot:8080
```

1 minute in particular rule, that i want to trigger in prometheus/rules

```
  - alert: CriticalDiskSpace
    expr: 100 - ((node_filesystem_avail_bytes{alias="hadoop_nodes",mountpoint="/bdp"} * 100) / node_filesystem_size_bytes{alias="hadoop_nodes",mountpoint="/bdp"}) > 80
    for: 1m
    labels:
      severity: critical
    annotations:
      description: "{{ $labels.instance }} is more than {{ $value }}% used."
      summary: "Instance {{ $labels.instance }} is low on disk space"
```
