### DISCUSSION TITLE
docker-compose env_file support

### DISCUSSION THREAD

**Discussion by lushndm** [metalmatze/alertmanager-bot#169] [Help/Support] [answered]
Hi!

This is part of my _docker-compose.yml_:
```
...
  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.4.3
    command:
      - --alertmanager.url=http://alertmanager:9093
      - --log.level=info
      - --store=bolt
      - --bolt.path=/data/bot.db
    env_file:
      - .alertmanager-bot.env
```

This is example of _.alertmanager-bot.env_ file:
```
TELEGRAM_ADMIN="123456789\n2345678"
TELEGRAM_TOKEN="345678901:MYtokenTokenToken-X-pXusjVxdrlCfdh"
```

When i'm trying set multiple admins in _environment_ section in _docker-compose.yml_ - everything works fine.

But when i'm trying set multiple admins in _.alertmanager-bot.env_ file i see that error :
`error parsing commandline arguments: strconv.ParseFloat: parsing "\"123456789\\n2345678\"": invalid syntax`
