### DISCUSSION TITLE
Set up chat

### DISCUSSION THREAD

**Discussion by tarkhil** [metalmatze/alertmanager-bot#176] [Help/Support]
I've connected my bot to chat, and when I command /alert, I get

This chat hasn't been setup to receive any alerts yet... 😕

Ask an administrator of the Alertmanager to add a webhook with /webhooks/telegram/__chat-id__ as URL.

What and where should I do?

```yaml
- name: 'telegram'
  webhook_configs:
  - send_resolved: true
    url: http://127.0.0.1:8080/webhooks/telegram/XXXXXXXX
```

did not help

**Comment by metalmatze** [comment]
Good feedback. I'll update the response to be more specific.
You need to add that YAML to the alertmanager configuration as receiver.
https://prometheus.io/docs/alerting/latest/configuration/#receiver

Afterwards you can configure alerts to be routed to that receiver. Exactly like anything else with alertmanager.

**Reply by tarkhil** [reply]
Sorry, it was a weekend beginning with the message "Our datacenter is down", and I may have some troubles reading.

What exactly should I do?

In my alertmanager.yml

```yaml
receivers:
- name: 'telegram'
  webhook_configs:
    - send_resolved: true
      url: 'http://127.0.0.1:8080/webhooks/telegram/-NNNNNNNNN'
```

But nothing happens
