### DISCUSSION TITLE
Deprecation of alertmanager-bot

### DISCUSSION THREAD

**Discussion by metalmatze** [metalmatze/alertmanager-bot#210] [General]
Alertmanager v0.24+ has Telegram support out of the box. Going forward, please simply use Alertmanager instead of this bot.
This project will be archived at the end of July.

This is your place to ask any questions until then.

**Comment by aaaler** [comment]
TL;DR migration path:
```
receivers:
- name: tg_new
  telegram_configs:
  - bot_token: '<bot:token>'
    chat_id: <chatid>
    api_url: "https://api.telegram.org"
    send_resolved: true
```
Prometheus-operator support still in progress. [should be released in v0.57.0 ](https://github.com/prometheus-operator/prometheus-operator/issues/4826)
