### DISCUSSION TITLE
Setting up Alerts

### DISCUSSION THREAD

**Discussion by chanyshev** [metalmatze/alertmanager-bot#211] [Help/Support]
Hi,
alert.rules.yml
```
 - alert: ContainerKilled
    expr: time() - container_last_seen > 60
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Container killed (instance {{ $labels.instance }})
      description: "A container has disappeared\n VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

Now my alerts look like this
![image](https://user-images.githubusercontent.com/44210753/167132784-28d82288-b0db-416b-9013-28bfd9796c78.png)

 1. How can I leave only instance, name, job ?
 2. How to remove empty lines?
 3. How do I set my icons for events?
Thank!
