### ISSUE TITLE
Missing host/summary from alert message

### ISSUE THREAD

**Issue by yangm97** [metalmatze/alertmanager-bot#110]
Sample from prometheus.yml:

```
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - '[ipv6:literal:here]:9100'
        - '[another:ipv6:literal:here]:9100'
```

Sample from alert_rules.yml:

```
groups:
- name: node.rules
  rules:
  - alert: HostDown
    expr: up{job="node_exporter"} == 0
    for: 3s
    labels:
      severity: error
    annotations:
      summary: "Instance {{ $labels.instance }} is DONW"
      description: "Node is unreachable for more than 5 minutes"
```

Screenshot from telegram:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/4412002/77167091-1946dd00-6a94-11ea-8939-e46866693c0e.png">
