### ISSUE TITLE
Key not found in store

### ISSUE THREAD

**Issue by keks2293** [metalmatze/alertmanager-bot#126]
How can I solve this
level=error ts=2020-08-31T07:07:10.297532726Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"

seen https://github.com/metalmatze/alertmanager-bot/issues/92 - /start not help

````
docker-compose.yml
version: "3"
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./conf:/etc/alertmanager/
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'

  alertmanager-bot:
    command:
    - --alertmanager.url=http://localhost:9093
    - --log.level=debug
    - --store=bolt
    - --bolt.path=/data/bot.db
    environment:
      TELEGRAM_ADMIN: 29xxxxx01
      TELEGRAM_TOKEN: 68xxxxx51:AAF_xzQ1-AH6Qj_h1z3uDmZFEEHsqzrI_9E
    image: metalmatze/alertmanager-bot:0.4.2
    ports:
    - 8080:8080
    restart: always
    volumes:
    - ./data:/data
```

alertmanager.yml
```
route:
   receiver: 'alertmananger-bot'
   group_interval: 10s

receivers:
- name: 'alertmananger-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot:8080/alert/-100140xxxxx61'
```
