### ISSUE TITLE
Status 403 not 200 when connect to webhook url.

### ISSUE THREAD

**Issue by ntk148v** [metalmatze/alertmanager-bot#17]
Hi, I've tried to use your bot with docker-compose. `/alerts` command works perfectly :ok_hand: , but when type `/start`, it don't work as expected. 

* LOGS in alertmanager container:

http://paste.openstack.org/show/718262/

* docker-compose file, you can see that, instead of mapping port 8080:8080, I map 8080 with 9194 in host machine.

https://github.com/ntk148v/prompose/blob/master/docker-compose.telegram.yml#L39

* In alertmanager configs, I point to telegram_bot host with port 9194.

Thank you, wait for your reply!

**Comment by metalmatze** [comment]
As you simply call the alertmanager `alertmanager` in your yaml that's all you need to contact it from the bot.
https://github.com/ntk148v/prompose/blob/master/docker-compose.telegram.yml#L58

```yaml
  telegram_bot:
    image: metalmatze/alertmanager-bot:0.2
    container_name: telegram_bot
    depends_on:
      - alertmanager
    environment:
      ALERTMANAGER_URL: http://alertmanager:9093
      LISTEN_ADDR: 0.0.0.0:8080
      BOLT_PATH: /data/bot.db
      STORE: bolt
      TELEGRAM_ADMIN: ${TELEGRAM_USER_ID}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    volumes:
      - telegram_bot_data:/data
    networks:
      - monitor-net
    ports:
      - 9194:8080
```
```diff
-ALERTMANAGER_URL: http://alertmanager_host:9093
+ALERTMANAGER_URL: http://alertmanager:9093
```
