### ISSUE TITLE
```failed to list alerts... context canceled``` message after ```/alerts``` command

### ISSUE THREAD

**Issue by abenaguev** [metalmatze/alertmanager-bot#18]
Hello. Just runed this bot up (and I like emoji in alerts :+1:), but it answer ```failed to list alerts... context canceled``` after ```/alerts``` command in 18 from 20 cases. ```/stop``` or ```/start``` commands seems to resolve this sometimes, but I'm not sure. I did try 0.2, 0.2.1. Bot live in swarm, if it's matter. Thanks in advance.
part of docker-compose:
```yaml
alertmanager:
    image: prom/alertmanager
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/config.yml
    networks:
      - monitoring
      - proxy
    volumes:
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=alertmanager.xxx.yyy
        - com.df.port=9093
        - com.df.httpsOnly=true
        - com.df.letsencrypt.host=alertmanager.xxx.yyy
        - com.df.letsencrypt.email=ssl@xxx.yyy
        - com.df.users=xxx:yyy

  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.2
    networks:
      - monitoring
    volumes:
      - alertmanager_bot_data:/data
    environment:
      ALERTMANAGER_URL: http://alertmanager:9093
      BOLT_PATH: /data/bot.db
      STORE: bolt
      TELEGRAM_ADMIN: '87654321'
      TELEGRAM_TOKEN: '12345678'
      LISTEN_ADDR: 0.0.0.0:8080
    volumes:
      - alertmanager_bot_data:/data
```
alertmanager:
```yaml
- name: 'alertmananger-bot'
    webhook_configs:
    - send_resolved: true
      url: 'http://alertmanager-bot:8080'
```
