### ISSUE TITLE
Not start

### ISSUE THREAD

**Issue by vanokg** [metalmatze/alertmanager-bot#20]
Hello, what I do wrong?

```
alertmanager-bot:
  image: metalmatze/alertmanager-bot:0.2
  environment:
    ALERTMANAGER_URL: http://alertmanager:9093
    BOLT_PATH: /data/bot.db
    STORE: bolt
    TELEGRAM_ADMIN: '1234567'
    TELEGRAM_TOKEN: XXX
  volumes:
  - /srv/monitoring/alertmanager-bot:/data
```

```
Attaching to dockprom_alertmanager-bot_1
alertmanager-bot_1  | error parsing commandline arguments: required flag --listen.addr not provided
alertmanager-bot_1  | usage: alertmanager-bot --alertmanager.url=ALERTMANAGER.URL --listen.addr=LISTEN.ADDR --store=STORE --telegram.admin=TELEGRAM.ADMIN --telegram.token=TELEGRAM.TOKEN [<flags>]
alertmanager-bot_1  | 
alertmanager-bot_1  | Bot for Prometheus' Alertmanager
alertmanager-bot_1  | 
alertmanager-bot_1  | Flags:
alertmanager-bot_1  |   -h, --help                     Show context-sensitive help (also try
alertmanager-bot_1  |                                  --help-long and --help-man).
alertmanager-bot_1  |       --alertmanager.url=ALERTMANAGER.URL  
alertmanager-bot_1  |                                  The URL that's used to connect to the
alertmanager-bot_1  |                                  alertmanager
alertmanager-bot_1  |       --bolt.path=BOLT.PATH      The path to the file where bolt persists its
alertmanager-bot_1  |                                  data
alertmanager-bot_1  |       --consul.url=CONSUL.URL    The URL that's used to connect to the consul
alertmanager-bot_1  |                                  store
alertmanager-bot_1  |       --listen.addr=LISTEN.ADDR  The address the alertmanager-bot listens on for
alertmanager-bot_1  |                                  incoming webhooks
alertmanager-bot_1  |       --store=STORE              The store to use
alertmanager-bot_1  |       --telegram.admin=TELEGRAM.ADMIN  
alertmanager-bot_1  |                                  The ID of the initial Telegram Admin
alertmanager-bot_1  |       --telegram.token=TELEGRAM.TOKEN  
alertmanager-bot_1  |                                  The token used to connect with Telegram
alertmanager-bot_1  | 
dockprom_alertmanager-bot_1 exited with code 2
```
