### ISSUE TITLE
Can't start bot in docker-compose

### ISSUE THREAD

**Issue by auterpring** [metalmatze/alertmanager-bot#201]
After starting, container always restarts 

logs:

level=error ts=2022-01-17T12:14:47.561730445Z caller=main.go:215 component=telegram msg="failed to create bot" err="bad response json: json: cannot unmarshal number 5090334062 into Go struct field User.Result.id of type int"

**Comment by murawew64** [comment]
I have equal issue today when i start ./alertmanager-bot-0.4.3-linux-arm (precompile version), don't know how to solve the problem.

**Comment by muhammadsiddiqbe** [comment]
Any news?

**Comment by Ch4t4r** [comment]
In my case it worked after I included `alertmanager-bot` in the command section.

```
  alertmanager_telegram_bot:
    image: alertmanager_bot:latest # Build locally for arm.
    container_name: prometheus_alertmanager_bot
    restart: always
    depends_on:
      - alertmanager
    volumes:
      - ./alertmanager_bot:/data
    networks: 
      - net_prometheus
    ports:
      - 9095:8080
    command:
        - 'alertmanager-bot'
        - '--alertmanager.url=http://alertmanager:9093'
        - '--log.level=info'
        - '--store=bolt'
        - '--bolt.path=/data/bot.db'
        - '--telegram.admin=1234567'
        - '--telegram.token=123:ABC'
    labels:
      org.label-schema.group: "monitoring"
```
