### ISSUE TITLE
Can't setup container with multiple Telegram Admins

### ISSUE THREAD

**Issue by MaartenMol** [metalmatze/alertmanager-bot#28]
Hello,

I can't seem to add multiple ID's to the telegram admins ENV setting. Here is my compose with single admin (this is working perfectly:

```
  alertmanager-bot:
    container_name: alertmanager-bot
    image: metalmatze/alertmanager-bot:0.3
    restart: unless-stopped
    ports:
      - 8888:8080
    environment:
      - TZ=Europe/Amsterdam
      - ALERTMANAGER_URL=http://alertmanager:9093
      - BOLT_PATH=/data/bot.db
      - STORE=bolt
      - LISTEN_ADDR=0.0.0.0:8080
      - TELEGRAM_ADMIN=**********
      - TELEGRAM_TOKEN=*************************************************
    volumes:
      - /opt/appdata/alertmanager-bot:/data
```
I have tried the following:

```
- TELEGRAM_ADMIN=**********,************
- TELEGRAM_ADMIN="**********,************"
- TELEGRAM_ADMIN='**********','************'
- TELEGRAM_ADMIN=['**********','************']
```

All of these result in the startup error that the syntax is incorrect.
