### ISSUE TITLE
alertmanager-bot telegram templates message

### ISSUE THREAD

**Issue by sandr30** [metalmatze/alertmanager-bot#31]
Hi! Help me tune alertmanager-bot telegram templates message. 

Alertmanager.yml
```
  receiver: 'alertmananger-bot'
  routes:
    - receiver: 'alertmananger-bot'
      group_wait: 45s
      group_interval: 10s
templates:
- '/data/monitoring/alertmanager/alert.tmpl'

receivers:
- name: 'alertmananger-bot'
  webhook_configs:
 provider: telegram
  text: '{{ template "telegram_message" . }}'
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'
```

Alertmanager no started and config Alertmanager.yml error. Help me
how to make alert.tmpl ?
