### ISSUE TITLE
Is it possible for the bot to notify me alerts automatically without typing "/alerts".

### ISSUE THREAD

**Issue by eieizahahayo** [metalmatze/alertmanager-bot#46]
Dear, metalmatze

I am very new to the Github issue session and this is my first time asking for help. I am sorry in advance If I did say something wrong.
Is it possible for the bot to notify me automatically when alerts occur?
The bot knows that there are alerts but it will only notify me when I use "/alerts".
I don't know if I did something wrong.
Here is my docker-compose:
```
alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.3.1
    container_name: alertmanager-bot
    environment:
      ALERTMANAGER_URL: http://alert_manager:9093
      BOLT_PATH: /data/bot.db
      STORE: bolt
      LISTEN_ADDR: alertmanager-bot:8080
      TELEGRAM_ADMIN: 'my-id'
      TELEGRAM_TOKEN: 'my-bot-token'
    networks: 
      - my-network
```

Thank you.
