### ISSUE TITLE
Please back to ENV instead of ARGS

### ISSUE THREAD

**Issue by freeseacher** [metalmatze/alertmanager-bot#7]
Current released version relies on ENV. that produces simple and clear docker-compose files. 
Current master uses ARGS so instead of having dicts with cool vars i have to add really log line with command

Probable bolt have to be default.

**Comment by metalmatze** [comment]
The current `master` still supports the exact same env vars as the previous commits. If that's not the case then please raise your voice again.
Closing because I didn't really change anything. It's just more options.

**Comment by freeseacher** [comment]
so here is mine docker-compose
```
....
  alertmanager-bot:
    image: freeseacher/alertmanager-bot:master
    environment:
      TELEGRAM_TOKEN: 263562XXX:XXXXX
      TELEGRAM_ADMIN: '-XXXX'
      ALERTMANAGER_URL: http://alertmanager:9093
      https_proxy: http://proxy:3128
      http_proxy: http://proxy:3128
    command: --listen.addr 0.0.0.0:8080 --store=bolt --bolt.path=/data/db.db --telegram.token=263562XXX:XXXXX --telegram.admin=-XXXX --alertmanager.url=http://alertmanager:9093
    volumes:
      - /data/prom_bot:/data
    labels:
      - traefik.enable=false
    networks:
      - front
      - proxy
....
```
ok. it seems that i got errors like 
`alertmanager-bot_1  | usage: alertmanager-boterror parsing commandline arguments: required flag --listen.addr not provided`
and
`alertmanager-bot_1  | error parsing commandline arguments: required flag --store not provided`
and stops trying to test other settings.

so issue can be just "renamed to provide sane defaults for and use ENV vars for new flags".

**Comment by metalmatze** [comment]
I don't know what you're doing there 😂 
You can either use env vars OR use flags. You don't need to use both. Just for the record. You're using my WIP `master`. 

What should work is:

```
  alertmanager-bot:
    image: freeseacher/alertmanager-bot:master
    environment:
      TELEGRAM_TOKEN: 263562XXX:XXXXX
      TELEGRAM_ADMIN: '-XXXX'
      ALERTMANAGER_URL: http://alertmanager:9093
      LISTEN_ADDR: 0.0.0.0:8080
      STORE: bolt
      BOLT_PATH: /data/db.db
    volumes:
      - /data/prom_bot:/data
    labels:
      - traefik.enable=false
    networks:
      - front
      - proxy
```
