### ISSUE TITLE
Alertmanager-bot on Kubernetes

### ISSUE THREAD

**Issue by monfardineL** [metalmatze/alertmanager-bot#90]
Although it's pretty simple, I think, I've made a few YAMLs to deploy the bot on kubernetes. If ya think it could be useful, tell me and I'll make a pull request. I'm using it to interact directly with Prometheus Operator.

**Comment by pieter91** [comment]
I've also created a Kubernetes Deployment and Service. I just quickly put them together, but am still having issues. Would love to see your take on it.

**Comment by monfardineL** [comment]
@pieter91 there you go:

[Pull Request 91](https://github.com/metalmatze/alertmanager-bot/pull/91)

**Comment by metalmatze** [comment]
Interesting this conversation just started. 
For years I've been running this bot on my Kubernetes cluster. I have generated Kuberentes manifests that are written with jsonnet. 
I'll add them to the repository and then maintain those going forward. They are pretty similar to what @monfardineL did in #91. :blush:

**Comment by runningman84** [comment]
Does the alertmanager bot work for you in k8s? I can use the bot  and ask for the status but I haven't got any alert message of it. This is my alert manager config

```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: alertmananger-bot
  group_by:
  - job
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
- name: alertmananger-bot
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://alertmanager-bot:8080
templates: []
```

Btw. I could provide you with my helm template for alert manager...

**Comment by monfardineL** [comment]
@runningman84 mine works with complete internal DNS name from receiver.

```
global:
  resolve_timeout: 5m
receivers:
- name: "null"
- name: 'alertmananger-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot.alertmanager-bot.svc.cluster.local:8080'
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: alertmananger-bot
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: "null"
```
