### ISSUE TITLE
error message failed to get chat list from store

### ISSUE THREAD

**Issue by runningman84** [metalmatze/alertmanager-bot#92]
How can I solve this error?
```
~ >>> kubectl logs alertmanager-bot-6db8cd95d6-s8zjm -n monitoring                                                                                         
level=info ts=2019-12-30T19:21:40.710926444Z caller=main.go:218 component=telegram msg="starting alertmanager-bot" version=0.4.0 revision=3dfe88e1cf837e0cb6c568d8a412a2c9334c54df buildDate=2019-02-19T20:49:19+0000 goVersion=go1.11.5
level=info ts=2019-12-30T19:21:40.711878302Z caller=main.go:260 component=webserver msg="starting webserver" addr=0.0.0.0:8080
level=error ts=2019-12-30T19:40:14.08012423Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"
level=error ts=2019-12-30T19:40:22.619262136Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"
level=error ts=2019-12-30T19:45:14.035310077Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"
level=error ts=2019-12-30T19:48:37.575757947Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"
level=error ts=2019-12-30T19:50:14.035449552Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"
```

**Comment by metalmatze** [comment]
You need to `/start` the chat and with that populate the list of chats (which is why this log message is saying that the chat list is empty)

**Comment by runningman84** [comment]
ok this works fine... but there seems to be a bug the duration in the alert messages is always "-", but I get the correct duration using the /alerts command.

What happens if I delete the bolt db, do I have to call the /start command again? In this case I would have to store it in a k8s pvc... what would happen if multiple instancdes of the bot would run at the same time?

**Comment by metalmatze** [comment]
> What happens if I delete the bolt db, do I have to call the /start command again?
Yes, that's right.
> In this case I would have to store it in a k8s pvc... what would happen if multiple instancdes of the bot would run at the same time?
Yes, I use a PVC for the bolt store. You could, however I never used it for long, run the etcd or consul baked store and run multiple bots. I wouldn't recommend running multiple with bolt, it might not even be possible as one container might lock the db.

**Comment by runningman84** [comment]
One last question would it be possible to alert if the watchdog messages aren't been sent anymore? This could be a useful feature....

**Comment by metalmatze** [comment]
Yes, I am doing that, however outside of this bot.
```yaml
    global:
      resolve_timeout: 5m
    route:
      receiver: telegram
      group_by: [ job, alertname, namespace ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      routes:
      - match:
          alertname: Watchdog
        receiver: 'healthchecks.io'
        group_interval: 1m
        repeat_interval: 1m
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: [ alertname, namespace, job, name ]
    receivers:
    - name: telegram
      webhook_configs:
      - url: http://alertmanager-bot:8080
    - name: 'healthchecks.io'
      webhook_configs:
      - url: https://hc-ping.com/XXX
        send_resolved: false
```

I am using a service called healthchecks.io for a WatchDog / DeadManSnitch alert. :+1:
