### ISSUE TITLE
Cant start because of default.tmpl in kubernetes

### ISSUE THREAD

**Issue by dijarllozana** [metalmatze/alertmanager-bot#94]
I have used the configuration files provided in #91 and everything seems to be fine when changing all the environment variables, and i have tried different solutions to fix the problem with the default.tmpl in kubernetes, i have mounted the volume separately because everytime it shows that ./default.tmpl does not exist.

My deployment file looks like this:
```
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alertmanager-bot-deploy
  labels:
    app: alertmanager-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-bot
  template:
    metadata:
      labels:
        app: alertmanager-bot
    spec:
      volumes:
        - name: ambot-data
          persistentVolumeClaim:
            claimName: amdata-pvc
        - name: template
          hostPath:
            path: /tmp/default.tmpl
      containers:
      - name: alertmanager-bot
        image: metalmatze/alertmanager-bot:0.4.0
#        env:
#        - name: ALERTMANAGER_URL
#          value: http://xxxxxxxx:9093
#        - name: BOLT_PATH
#          value: /data/chat.db
#        - name: STORE
#          value: bolt
#        - name: LISTEN_ADDR
#          value: 0.0.0.0:8080
#        - name: TELEGRAM_TOKEN
#          value: 'xxxxxxxxxxxxxxx'
#        - name: TELEGRAM_ADMIN
#          value: "xxxxxxxxxx"
#        - name: TEMPLATE_PATHS
#          value: /default.tmpl
        envFrom:
        - secretRef:
            name: telegrambot-token
            optional: false
        - configMapRef:
            name: alertmanager-bot-configmap
            optional: false
        volumeMounts:
        - name: ambot-data
          mountPath: /data
          volumes:
        - mountPath: /templates/default.tmpl
          name: template
```

As you can see, i also tried using the environment variables directly into the deployment file but to no avail.
I cant for the life of me find where the default.tmpl file is.
I have tried /templates/default.tmpl and only /default.tmpl aswell but either it cant find the file or it says that its trying to mount a directory into a file or vice versa. 
I hope i have given enough information to help me solve this issue
