### ISSUE TITLE
Docker image not start

### ISSUE THREAD

**Issue by artemkamolodets** [metalmatze/alertmanager-bot#95]
Hello.
Image is fail on start.

Error message:
```
prometheus_telegram_bot    | error parsing commandline arguments: required flag '--alertmanager.url' with default value that will never be used
prometheus_telegram_bot    | alertmanager-bot: error: required flag '--listen.addr' with default value that will never be used
prometheus_telegram_bot    | alertmanager-bot: error: required flag '--alertmanager.url' with default value that will never be used
prometheus_telegram_bot    | error parsing commandline arguments: required flag '--alertmanager.url' with default value that will never be used
prometheus_telegram_bot    | alertmanager-bot: error: required flag '--alertmanager.url' with default value that will never be used
prometheus_telegram_bot    | error parsing commandline arguments: required flag '--alertmanager.url' with default value that will never be used
prometheus_telegram_bot exited with code 1
```

My compose:
```yaml
---
version: '3'
services:
  prometheus_telegram_bot:
    image: metalmatze/alertmanager-bot:0.4.1
    restart: always
    container_name: prometheus_telegram_bot
    env_file:
      - ./env
    networks:
      - prometheus
    volumes:
      - "data:/data"

networks:
  prometheus:
    external: true

volumes:
  data:
```

My env file:
```
LISTEN_ADDR=0.0.0.0:8080
ALERTMANAGER_URL=http://prometheus_alert_manager:9093
BOLT_PATH=/data/bolt.db
STORE=bolt
TELEGRAM_TOKEN=<some token here>
TELEGRAM_ADMIN=<some id here>
TEMPLATE_PATHS=/templates/default.tmpl
```

Please help.
