### ISSUE TITLE
Question: Empty variables

### ISSUE THREAD

**Issue by rmalenko** [metalmatze/alertmanager-bot#98]
Hello,

Could you help me understand where I wrong, please? I have being received unprocessed variables.

This is the test alert
```
---
groups:
- name: servers.traffic
  rules:
  - alert: Server {{.labels.servername }} {{ $labels.job }} {{ $labels.exported_job
      }} exceeded traffic limit {{ $value }} {{ $labels }
    expr: servertraffics_limit-(servertraffics_up+servertraffics_down)
      > 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Server {{ $labels.servername }} exceeded traffic limit {{ $value }}
      description: "{{ $labels.servername }} on {{ $labels.serverlocation }} exceeded\
        \ {{ $labels.traflimits }} TB traffic limit"
```
and receive variables like this
![image](https://user-images.githubusercontent.com/1563560/72734790-2f731280-3ba3-11ea-85f1-46541d413203.png)

**Comment by metalmatze** [comment]
That's nothing specific about the bot.
You don't put the variables in the alertname.

```diff
- Server {{.labels.servername }} {{ $labels.job }} {{ $labels.exported_job }} exceeded traffic limit {{ $value }} {{ $labels }
+ ServerExceedsTBLimit
```

The templating will happen in the alertmanager-bot afterwards and it will concatenate your strings.

**Comment by metalmatze** [comment]
Another thing is, for the messages to appear via the alertmanager-bot you need to use the `message` annotation, rather then `summary` and `description`.
That's just the default of the template I ship with the bot:
https://github.com/metalmatze/alertmanager-bot/blob/master/default.tmpl#L5

You can change that template though, if you prefer summary and description.

**Comment by rmalenko** [comment]
metalmatze thank you for help. I have sorted out this.

```
groups:
- name: servers.traffic
  rules:
  - alert: A server exceeds TB limit
    expr: servertraffics_limit-((servertraffics_up+servertraffics_down)/1000000000000) < 0
    for: 5m
    labels:
      severity: warning
    annotations:
      message: Server {{ $labels.servername }} on {{ $labels.serverlocation }} exceeded {{ $value }} TB traffic limit
```
